// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SmartReview.DataAnalyzer.Sentiment.Models
{
    public class ModelInput
    {
        [ColumnName("stars"), LoadColumn(0)]
        public bool Stars { get; set; }


        [ColumnName("text"), LoadColumn(1)]
        public string Text { get; set; }


    }
}
